#coding=utf-8
pocs=[
    {"requests_option":"GET",
     "url":["/jmx-console/HtmlAdaptor?action=inspectMBean&name=jboss.system:type=ServerInfo"],
     "params":[],
     "data":[],
     "flag":[],
     "success":"/jmx-console/HtmlAdaptor?action=inspectMBean&name=jboss.system:type=ServerInfo",
     "fail":"",
     "end":"/jmx-console/HtmlAdaptor?action=inspectMBean&name=jboss.system:type=ServerInfo 扫描完成",
     "admin_bursk":"",
     "username":[],
     "password":[],
     },
    {"requests_option":"GET",
     "url":["/web-console/Invoker"],
     "params":[],
     "data":[],
     "flag":[],
     "success":"/web-console/Invoker",
     "fail":"",
     "end":"/web-console/Invoker 扫描完成",
     "admin_bursk":"",
     "username":[],
     "password":[],
     },
    {"requests_option":"GET",
     "url":["/invoker/JMXInvokerServlet"],
     "params":[],
     "data":[],
     "flag":[],
     "success":"/invoker/JMXInvokerServlet",
     "fail":"",
     "end":"/invoker/JMXInvokerServlet 扫描完成",
     "admin_bursk":"",
     "username":[],
     "password":[],
     },
    {"requests_option":"GET",
     "url":["/admin-console/"],
     "params":[],
     "data":[],
     "flag":[],
     "success":"/admin-console/",
     "fail":"",
     "end":"/admin-console/ 扫描完成",
     "admin_bursk":"",
     "username":[],
     "password":[],
     },
]


